---
language: python
dist: bionic
python:
  - "3.6.7"

addons:
  postgresql: "10"

cache: pip

before_install:
  - sudo apt-get install -y lp-solve
  - sudo apt-get install -y postgresql-server-dev-10

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"

before_script:
  - psql -c 'create database mueslitest;' -U postgres
  - psql -c 'create database muesli;' -U postgres
  - psql -d muesli -U postgres < muesli.sql
  - cp muesli.yml.example muesli.yml
  # ugly hack
  - sudo wget https://www.mathi.uni-heidelberg.de/~jvisintini/lp_solve -O /usr/bin/lp_solve
  - sudo wget https://www.mathi.uni-heidelberg.de/~jvisintini/libxli_DIMACS.so -O /usr/lib/lp_solve/libxli_DIMACS.so
  - sudo python -m smtpd -n -c DebuggingServer localhost:25 &

# command to run tests
script: MUESLI_PATH=$(pwd) py.test --cov=muesli muesli/tests/*

after_script:
  - codecov
  - pylint --disable=R0801,R0903,C0103,C0301,C0111 muesli.web.api muesli.web.viewsApi muesli.tests.api
