---
version: '3.2'

services:
  postgres:
    image: 'postgres:10'
    environment:
      POSTGRES_DB: muesli
      POSTGRES_USER: muesli
      POSTGRES_PASSWORD: mueslipw
    volumes:
      - './docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh'
      - './muesli.sql:/muesli.sql'
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
  muesli:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: muesli:latest
    depends_on:
      - postgres
    environment:
      MUESLI_DEVMODE: 1
      MUESLI_DB_CONNECTION_STRING: postgresql://muesli:mueslipw@postgres/muesli
      MUESLI_MAILSERVER_HOST: mailcatcher
      MUESLI_MAILSERVER_PORT: 1025

  mailcatcher:
    image: 'schickling/mailcatcher'

volumes:
  db-data:
