version: '2'
services:
  muesli:
    image: ghcr.io/muesli-hd/muesli:production
    ports:
      - "127.0.0.1:8033:8080"
      - "127.0.0.1:8034:8081"
    restart: always
    volumes:
      - "/opt/muesli4/muesli.yml:/opt/muesli4/muesli.yml"
    depends_on:
      - postgres
      - redis
    environment:
      MUESLI_DB_CONNECTION_STRING: postgresql://muesli:mueslipw@postgres/muesli
      MUESLI_MAILSERVER_HOST: mailcatcher
      MUESLI_MAILSERVER_PORT: 1025
  redis:
    image: redis:6-alpine
