version: '2'
services:
  muesli:
    build:
      context: https://github.com/muesli-hd/muesli.git#production
    image: muesli
    container_name: muesli
    ports:
      - "127.0.0.1:8033:8080"
      - "127.0.0.1:8034:8081"
    network_mode: "bridge"
    restart: always
    volumes:
      - "/opt/muesli4/muesli.yml:/opt/muesli4/muesli.yml"
      - "/opt/muesli4/alembic.ini:/opt/muesli4/alembic.ini"
