---
version: '3.2'

services:
  postgres:
    container_name: muesli_postgres_testrunner
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: muesli
      POSTGRES_USER: muesli
      POSTGRES_PASSWORD: mueslipw
    volumes:
      - '../deployment/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh'

  muesli:
    image: "muesli:tests"
    container_name: muesli_testrunner
    build:
      context: ..
      dockerfile: ./docker_run_tests/Dockerfile
    volumes:
      - '../:/opt/muesli4'
    environment:
      MUESLI_DB_HOST: postgres
      MUESLI_DB: muesli
      MUESLI_DB_USER: muesli
      MUESLI_DB_PASSWORD: mueslipw
    depends_on:
      - postgres
